"""Bluetooth SIG UUID registry helpers.

This module stores well-known GATT service/characteristic/descriptor names
and exposes lookup helpers used by both GUI and CLI layers.
"""

# Helper: normalize any UUID to full 128-bit lowercase string
def normalize_uuid(uuid: str) -> str:
    uuid = uuid.strip().lower()
    # 16-bit short form (4 hex digits)
    if len(uuid) == 4:
        return f"0000{uuid}-0000-1000-8000-00805f9b34fb"
    # 32-bit short form (8 hex digits)
    if len(uuid) == 8:
        return f"{uuid}-0000-1000-8000-00805f9b34fb"
    return uuid


# ── Services ─────────────────────────────────────────────────────────────────

GATT_SERVICES: dict[str, str] = {
    "1800": "Generic Access",
    "1801": "Generic Attribute",
    "1802": "Immediate Alert",
    "1803": "Link Loss",
    "1804": "Tx Power",
    "1805": "Current Time Service",
    "1806": "Reference Time Update Service",
    "1807": "Next DST Change Service",
    "1808": "Glucose",
    "1809": "Health Thermometer",
    "180a": "Device Information",
    "180d": "Heart Rate",
    "180e": "Phone Alert Status Service",
    "180f": "Battery Service",
    "1810": "Blood Pressure",
    "1811": "Alert Notification Service",
    "1812": "Human Interface Device",
    "1813": "Scan Parameters",
    "1814": "Running Speed and Cadence",
    "1815": "Automation IO",
    "1816": "Cycling Speed and Cadence",
    "1818": "Cycling Power",
    "1819": "Location and Navigation",
    "181a": "Environmental Sensing",
    "181b": "Body Composition",
    "181c": "User Data",
    "181d": "Weight Scale",
    "181e": "Bond Management Service",
    "181f": "Continuous Glucose Monitoring",
    "1820": "Internet Protocol Support Service",
    "1821": "Indoor Positioning",
    "1822": "Pulse Oximeter Service",
    "1823": "HTTP Proxy",
    "1824": "Transport Discovery",
    "1825": "Object Transfer Service",
    "1826": "Fitness Machine",
    "1827": "Mesh Provisioning Service",
    "1828": "Mesh Proxy Service",
    "1829": "Reconnection Configuration",
    "183a": "Insulin Delivery",
    "183b": "Binary Sensor",
    "183c": "Emergency Configuration",
    "183e": "Physical Activity Monitor",
    "1843": "Audio Stream Control Service",
    "1844": "Broadcast Audio Scan Service",
    "1845": "Published Audio Capabilities Service",
    "1846": "Basic Audio Announcement Service",
    "1847": "Broadcast Audio Announcement Service",
    "1848": "Common Audio Service",
    "1849": "Hearing Access Service",
    "184a": "Telephony and Media Audio Service",
    "184b": "Public Broadcast Announcement Service",
    "184c": "Electronic Shelf Label Service",
    "184d": "Gaming Audio Service",
    "1850": "Coordinated Set Identification Service",
    "1851": "Device Time",
    "1852": "Media Control Service",
    "1853": "Generic Media Control Service",
    "1854": "Constant Tone Extension",
    "1855": "Telephone Bearer Service",
    "1856": "Generic Telephone Bearer Service",
    "1857": "Microphone Control",
    "1858": "Audio Input Control",
    "1859": "Volume Control Service",
    "185a": "Volume Offset Control Service",
}

# ── Characteristics ───────────────────────────────────────────────────────────

GATT_CHARACTERISTICS: dict[str, str] = {
    "2a00": "Device Name",
    "2a01": "Appearance",
    "2a02": "Peripheral Privacy Flag",
    "2a03": "Reconnection Address",
    "2a04": "Peripheral Preferred Connection Parameters",
    "2a05": "Service Changed",
    "2a06": "Alert Level",
    "2a07": "Tx Power Level",
    "2a08": "Date Time",
    "2a09": "Day of Week",
    "2a0a": "Day Date Time",
    "2a0c": "Exact Time 256",
    "2a0d": "DST Offset",
    "2a0e": "Time Zone",
    "2a0f": "Local Time Information",
    "2a11": "Time with DST",
    "2a12": "Time Accuracy",
    "2a13": "Time Source",
    "2a14": "Reference Time Information",
    "2a16": "Time Update Control Point",
    "2a17": "Time Update State",
    "2a18": "Glucose Measurement",
    "2a19": "Battery Level",
    "2a1c": "Temperature Measurement",
    "2a1d": "Temperature Type",
    "2a1e": "Intermediate Temperature",
    "2a21": "Measurement Interval",
    "2a22": "Boot Keyboard Input Report",
    "2a23": "System ID",
    "2a24": "Model Number String",
    "2a25": "Serial Number String",
    "2a26": "Firmware Revision String",
    "2a27": "Hardware Revision String",
    "2a28": "Software Revision String",
    "2a29": "Manufacturer Name String",
    "2a2a": "IEEE 11073-20601 Regulatory Certification Data List",
    "2a2b": "Current Time",
    "2a2c": "Magnetic Declination",
    "2a31": "Scan Refresh",
    "2a32": "Boot Keyboard Output Report",
    "2a33": "Boot Mouse Input Report",
    "2a34": "Glucose Measurement Context",
    "2a35": "Blood Pressure Measurement",
    "2a36": "Intermediate Cuff Pressure",
    "2a37": "Heart Rate Measurement",
    "2a38": "Body Sensor Location",
    "2a39": "Heart Rate Control Point",
    "2a3f": "Alert Status",
    "2a40": "Ringer Control Point",
    "2a41": "Ringer Setting",
    "2a42": "Alert Category ID Bit Mask",
    "2a43": "Alert Category ID",
    "2a44": "Alert Notification Control Point",
    "2a45": "Unread Alert Status",
    "2a46": "New Alert",
    "2a47": "Supported New Alert Category",
    "2a48": "Supported Unread Alert Category",
    "2a49": "Blood Pressure Feature",
    "2a4a": "HID Information",
    "2a4b": "Report Map",
    "2a4c": "HID Control Point",
    "2a4d": "Report",
    "2a4e": "Protocol Mode",
    "2a4f": "Scan Interval Window",
    "2a50": "PnP ID",
    "2a51": "Glucose Feature",
    "2a52": "Record Access Control Point",
    "2a53": "RSC Measurement",
    "2a54": "RSC Feature",
    "2a55": "SC Control Point",
    "2a56": "Digital",
    "2a58": "Analog",
    "2a5a": "Aggregate",
    "2a5b": "CSC Measurement",
    "2a5c": "CSC Feature",
    "2a5d": "Sensor Location",
    "2a5e": "PLX Spot-Check Measurement",
    "2a5f": "PLX Continuous Measurement",
    "2a60": "PLX Features",
    "2a63": "Cycling Power Measurement",
    "2a64": "Cycling Power Vector",
    "2a65": "Cycling Power Feature",
    "2a66": "Cycling Power Control Point",
    "2a67": "Location and Speed",
    "2a68": "Navigation",
    "2a69": "Position Quality",
    "2a6a": "LN Feature",
    "2a6b": "LN Control Point",
    "2a6c": "Elevation",
    "2a6d": "Pressure",
    "2a6e": "Temperature",
    "2a6f": "Humidity",
    "2a70": "True Wind Speed",
    "2a71": "True Wind Direction",
    "2a72": "Apparent Wind Speed",
    "2a73": "Apparent Wind Direction",
    "2a74": "Gust Factor",
    "2a75": "Pollen Concentration",
    "2a76": "UV Index",
    "2a77": "Irradiance",
    "2a78": "Rainfall",
    "2a79": "Wind Chill",
    "2a7a": "Heat Index",
    "2a7b": "Dew Point",
    "2a7d": "Descriptor Value Changed",
    "2a7e": "Aerobic Heart Rate Lower Limit",
    "2a7f": "Aerobic Threshold",
    "2a80": "Age",
    "2a81": "Anaerobic Heart Rate Lower Limit",
    "2a82": "Anaerobic Heart Rate Upper Limit",
    "2a83": "Anaerobic Threshold",
    "2a84": "Aerobic Heart Rate Upper Limit",
    "2a85": "Date of Birth",
    "2a86": "Date of Threshold Assessment",
    "2a87": "Email Address",
    "2a88": "Fat Burn Heart Rate Lower Limit",
    "2a89": "Fat Burn Heart Rate Upper Limit",
    "2a8a": "First Name",
    "2a8b": "Five Zone Heart Rate Limits",
    "2a8c": "Gender",
    "2a8d": "Heart Rate Max",
    "2a8e": "Height",
    "2a8f": "Hip Circumference",
    "2a90": "Last Name",
    "2a91": "Maximum Recommended Heart Rate",
    "2a92": "Resting Heart Rate",
    "2a93": "Sport Type for Aerobic and Anaerobic Thresholds",
    "2a94": "Three Zone Heart Rate Limits",
    "2a95": "Two Zone Heart Rate Limit",
    "2a96": "VO2 Max",
    "2a97": "Waist Circumference",
    "2a98": "Weight",
    "2a99": "Database Change Increment",
    "2a9a": "User Index",
    "2a9b": "Body Composition Feature",
    "2a9c": "Body Composition Measurement",
    "2a9d": "Weight Measurement",
    "2a9e": "Weight Scale Feature",
    "2a9f": "User Control Point",
    "2aa0": "Magnetic Flux Density - 2D",
    "2aa1": "Magnetic Flux Density - 3D",
    "2aa2": "Language",
    "2aa3": "Barometric Pressure Trend",
    "2aa4": "Bond Management Control Point",
    "2aa5": "Bond Management Features",
    "2aa6": "Central Address Resolution",
    "2aa7": "CGM Measurement",
    "2aa8": "CGM Feature",
    "2aa9": "CGM Status",
    "2aaa": "CGM Session Start Time",
    "2aab": "CGM Session Run Time",
    "2aac": "CGM Specific Ops Control Point",
    "2aad": "Indoor Positioning Configuration",
    "2aae": "Latitude",
    "2aaf": "Longitude",
    "2ab0": "Local North Coordinate",
    "2ab1": "Local East Coordinate",
    "2ab2": "Floor Number",
    "2ab3": "Altitude",
    "2ab4": "Uncertainty",
    "2ab5": "Location Name",
    "2ab6": "URI",
    "2ab7": "HTTP Headers",
    "2ab8": "HTTP Status Code",
    "2ab9": "HTTP Entity Body",
    "2aba": "HTTP Control Point",
    "2abb": "HTTPS Security",
    "2abc": "TDS Control Point",
    "2abd": "OTS Feature",
    "2abe": "Object Name",
    "2abf": "Object Type",
    "2ac0": "Object Size",
    "2ac1": "Object First-Created",
    "2ac2": "Object Last-Modified",
    "2ac3": "Object ID",
    "2ac4": "Object Properties",
    "2ac5": "Object Action Control Point",
    "2ac6": "Object List Control Point",
    "2ac7": "Object List Filter",
    "2ac8": "Object Changed",
    "2ac9": "Resolvable Private Address Only",
    "2acc": "Fitness Machine Feature",
    "2acd": "Treadmill Data",
    "2ace": "Cross Trainer Data",
    "2acf": "Step Climber Data",
    "2ad0": "Stair Climber Data",
    "2ad1": "Rower Data",
    "2ad2": "Indoor Bike Data",
    "2ad3": "Training Status",
    "2ad4": "Supported Speed Range",
    "2ad5": "Supported Inclination Range",
    "2ad6": "Supported Resistance Level Range",
    "2ad7": "Supported Heart Rate Range",
    "2ad8": "Supported Power Range",
    "2ad9": "Fitness Machine Control Point",
    "2ada": "Fitness Machine Status",
    "2adb": "Mesh Provisioning Data In",
    "2adc": "Mesh Provisioning Data Out",
    "2add": "Mesh Proxy Data In",
    "2ade": "Mesh Proxy Data Out",
    "2ae0": "Average Current",
    "2ae1": "Average Voltage",
    "2ae2": "Boolean",
    "2ae3": "Chromatic Distance from Planckian",
    "2ae4": "Chromaticity Coordinates",
    "2ae5": "Chromaticity in CCT and Duv Values",
    "2ae6": "Chromaticity Tolerance",
    "2ae7": "CIE 13.3-1995 Color Rendering Index",
    "2ae8": "Coefficient",
    "2ae9": "Correlated Color Temperature",
    "2aea": "Count 16",
    "2aeb": "Count 24",
    "2aec": "Country Code",
    "2aed": "Date UTC",
    "2aee": "Electric Current",
    "2aef": "Electric Current Range",
    "2af0": "Electric Current Specification",
    "2af1": "Electric Current Statistics",
    "2af2": "Energy",
    "2af3": "Energy in a Period of Day",
    "2af4": "Event Statistics",
    "2af5": "Fixed String 16",
    "2af6": "Fixed String 24",
    "2af7": "Fixed String 36",
    "2af8": "Fixed String 8",
    "2af9": "Generic Level",
    "2afa": "Global Trade Item Number",
    "2afb": "Illuminance",
    "2afc": "Luminous Efficacy",
    "2afd": "Luminous Energy",
    "2afe": "Luminous Exposure",
    "2aff": "Luminous Flux",
}

# ── Descriptors ───────────────────────────────────────────────────────────────

GATT_DESCRIPTORS: dict[str, str] = {
    "2900": "Characteristic Extended Properties",
    "2901": "Characteristic User Description",
    "2902": "Client Characteristic Configuration",
    "2903": "Server Characteristic Configuration",
    "2904": "Characteristic Presentation Format",
    "2905": "Characteristic Aggregate Format",
    "2906": "Valid Range",
    "2907": "External Report Reference",
    "2908": "Report Reference",
    "2909": "Number of Digitals",
    "290a": "Value Trigger Setting",
    "290b": "Environmental Sensing Configuration",
    "290c": "Environmental Sensing Measurement",
    "290d": "Environmental Sensing Trigger Setting",
    "290e": "Time Trigger Setting",
    "290f": "Complete BR-EDR Transport Block Data",
}


def _extract_short_uuid(uuid: str) -> str:
    """Return the canonical 16-bit key used for SIG table lookups."""
    uuid = uuid.strip().lower()
    # Standard 128-bit SIG UUID: 0000XXXX-0000-1000-8000-00805f9b34fb
    if len(uuid) == 36 and uuid.endswith("-0000-1000-8000-00805f9b34fb"):
        return uuid[4:8]
    # Already short (4 or 8 hex chars)
    if len(uuid) in (4, 8):
        return uuid[-4:]
    return uuid


def lookup_service(uuid: str) -> str | None:
    return GATT_SERVICES.get(_extract_short_uuid(uuid))


def lookup_characteristic(uuid: str) -> str | None:
    return GATT_CHARACTERISTICS.get(_extract_short_uuid(uuid))


def lookup_descriptor(uuid: str) -> str | None:
    return GATT_DESCRIPTORS.get(_extract_short_uuid(uuid))


def lookup_any(uuid: str) -> str | None:
    """Look up a UUID across services, characteristics, and descriptors."""
    short = _extract_short_uuid(uuid)
    return (
        GATT_SERVICES.get(short)
        or GATT_CHARACTERISTICS.get(short)
        or GATT_DESCRIPTORS.get(short)
    )
